import advancedSERPTrackingService from './advancedSERPTrackingService';

export const advancedSERPSerFeatureTrackingService = advancedSERPTrackingService;
export default advancedSERPSerFeatureTrackingService;
