import competitorIntelligenceService from './competitorIntelligenceService';

export const competitorIntelligenceSystemService = competitorIntelligenceService;
export default competitorIntelligenceSystemService;
