name: Reusable Node.js Setup

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '20'
      cache-npm:
        description: 'Whether to cache npm dependencies'
        required: false
        type: boolean
        default: true
      install-command:
        description: 'Install command to run'
        required: false
        type: string
        default: 'npm ci --ignore-scripts'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-npm && 'npm' || '' }}

      - name: Cache Node.js modules
        if: inputs.cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: ${{ inputs.install-command }}

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"