name: Reusable Secure Git Push

on:
  workflow_call:
    inputs:
      commit-message:
        description: 'Commit message to use'
        required: true
        type: string
      files-to-add:
        description: 'Files to add (comma-separated)'
        required: false
        type: string
        default: ''
      commit-author:
        description: 'Commit author email'
        required: false
        type: string
        default: 'action@github.com'
      commit-author-name:
        description: 'Commit author name'
        required: false
        type: string
        default: 'GitHub Action'

jobs:
  secure-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --local user.email "${{ inputs.commit-author }}"
          git config --local user.name "${{ inputs.commit-author-name }}"

      - name: Add files
        if: inputs.files-to-add != ''
        run: |
          # Split files by comma and add each with error handling
          IFS=',' read -ra FILES <<< "${{ inputs.files-to-add }}"
          for file in "${FILES[@]}"; do
            # Remove whitespace and add file if it exists
            file=$(echo "$file" | xargs)
            if [ -n "$file" ]; then
              git add "$file" || echo "File $file not found or cannot be added"
            fi
          done

      - name: Check for changes and commit
        run: |
          # Prüfen ob Änderungen vorhanden sind
          if ! git diff --quiet && ! git diff --staged --quiet; then
            echo "Changes detected, committing..."
            git commit -m "${{ inputs.commit-message }}"

            # Atomischer Push mit Retry-Mechanismus
            for i in {1..3}; do
              if git push; then
                echo "Push successful on attempt $i"
                break
              else
                echo "Push attempt $i failed, retrying in 5 seconds..."
                sleep 5
              fi
            done
          else
            echo "No changes to commit"
          fi